### ISSUE TITLE
Readability of output in VSCode (non-tabular view)

### ISSUE THREAD

**Issue by buildreactive** [elixir-tools/elixir-tools.vscode#9]
Readability of Credo output is challenging in VSCode using this plugin (compared, at least, to other behavior such as the compiler and approach used by the 'Credo (Elixir Linter)' plugin).

Specifially, if you view issues in the *tree view* (not tabular view), the output is hard to manage because:
1. Everything is expanded by default and extremely verbose, so each individual issue requires excessive scrolling (or, collapse each item).
2. Mouse-over hover causes a tooltip with the full text to appear, which often obstructs underlying text in annoying ways.

Example:
<img width="936" alt="image" src="https://github.com/elixir-tools/elixir-tools.vscode/assets/5351337/df10e0a8-681f-4f5c-9b42-f77a74ab0efc">

I think it would make more sense to emulate the approach taken by the native compiler output and 'Credo (Elixir Linter)' plugin, specifically:
1. Everything is collapsed by default
2. Only summary information is presented in the "Problems" tab, save the full tooltip display for actual code hover.

Example:
<img width="936" alt="image" src="https://github.com/elixir-tools/elixir-tools.vscode/assets/5351337/6d3987fe-cbd2-4394-b94b-70dcd085cb0e">

This also points out another (related) issue, in that code highlighted is currently broken and only underlines the first character of a problem statement (versus the entire statement).

Example:
<img width="936" alt="image" src="https://github.com/elixir-tools/elixir-tools.vscode/assets/5351337/bbbc8a5d-dec6-4c12-9bd9-82cb6955e599">

**Comment by mhanberg** [comment]
I tend to agree with your point that it is hard to read, but i'll make a few clarifications.

- I am not sure if I have control over the tooltips or the collapse/expanded default behavior. The problems pane is for all diagnostics, not just a single extension.
- The diagnostics are not actually "expanded", I believe they are just multiline. The screenshot you shared with the other credo extension are simply single line diagnostics. I'm not sure what the tooltip would look like for the other extension.
- The last thing "in that code highlighted is currently broken and only underlines the first character of a problem statement (versus the entire statement)." is not broken, that is a limitation from Credo currently. Issues Credo finds are only presented with the line and column number (not a start line/col and end line/col).  I opted to do that rather than fake it with the whole line. In Neovim, I get some virtual text which makes it easier to see, but I agree that it's hard to see in VSCode sometimes.

All that being said, I'll look into if there is a way report the diagnostics in a way that is more legible.

**Comment by mhanberg** [comment]
> The diagnostics are not actually "expanded", I believe they are just multiline. The screenshot you shared with the other credo extension are simply single line diagnostics. I'm not sure what the tooltip would look like for the other extension.

this statement is false, you are correct here. looking into if the behavior can be optimized

**Comment by mhanberg** [comment]
From what I can tell, this is the same behavior that is observed when ElixirLS has Dialyzer enabled and it finds lots of errors. Dialyzer output can also contain large, multi line messages

**Comment by mhanberg** [comment]
Okay, with regard to readability, in an upcoming release, the diagnostics should look like this: 
<img width="1236" alt="image" src="https://github.com/elixir-tools/elixir-tools.vscode/assets/5523984/e129d854-56a6-4f4e-b99b-5b278d920e02">

**Comment by mhanberg** [comment]
Closed by https://github.com/elixir-tools/credo-language-server/pull/52
